services:
  llmster:
    image: ghcr.io/psauxwwf/llmster:nvidia
    build:
      args:
        CUDA: "1"
        LMS_INSTALL_HOME: /root
      cache_from:
        - type=registry,ref=ghcr.io/psauxwwf/llmster:nvidia
    gpus: all
    environment:
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: compute,utility
